#!/usr/bin/env node
/**
 * Emits the supervisor config for this machine (M6).
 *
 * ## Why this is generated rather than committed
 *
 * A launchd plist and a systemd unit both need ABSOLUTE paths — to the repo, to
 * node, to the log files. This project's first standing portability rule is
 * "zero absolute paths anywhere in the tree, including tests, scripts, and
 * docs", enforced by `npm run check:portability`. A committed plist would
 * either violate that check or contain someone else's home directory.
 *
 * §12 resolves it directly: "treat launchd/systemd as a thin wrapper generated
 * at deploy time." So the paths are discovered here, at generation time, on the
 * machine that will actually run the thing. The output is deploy artifact, not
 * source, and is gitignored.
 *
 *   node scripts/generate-service.mjs launchd  > ~/Library/LaunchAgents/io.dram51.watchfloor.scheduler.plist
 *   node scripts/generate-service.mjs systemd   > ~/.config/systemd/user/watchfloor.service
 *
 * Both point at scripts/scheduler-service.sh, which runs the migration before
 * the scheduler — see that file for why those are one step.
 */
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const wrapper = join(repoRoot, 'scripts', 'scheduler-service.sh');

// The label matches the owner's existing convention on this machine
// (io.dram51.tradingbot.*), so `launchctl list | grep dram51` shows everything
// they run in one place.
const LABEL = 'io.dram51.watchfloor.scheduler';

function logDir() {
  // WF_LOG_DIR is relative by schema. Resolve it here, where absolute is the
  // whole point, and fall back to ./logs rather than guessing /var/log — which
  // a user-level agent cannot write to anyway.
  const configured = process.env.WF_LOG_DIR ?? './logs';
  return resolve(repoRoot, configured);
}

function nodeBin() {
  // Which node the supervisor should use. `process.execPath` is this one, which
  // is the one the operator just tested with -- better than trusting a PATH the
  // supervisor may not share. launchd notably does NOT inherit a login shell's
  // PATH, which is the single most common reason a working command fails as an
  // agent.
  return process.execPath;
}

function npmBin() {
  try {
    return execFileSync('command', ['-v', 'npm'], { shell: true, encoding: 'utf8' }).trim();
  } catch {
    return 'npm';
  }
}

function escapeXml(value) {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

function launchd() {
  const logs = logDir();
  const binDir = dirname(nodeBin());
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Generated by scripts/generate-service.mjs on ${new Date().toISOString()}.
  Regenerate rather than editing: the paths below are this machine's.

    launchctl unload ~/Library/LaunchAgents/${LABEL}.plist   # if already loaded
    node scripts/generate-service.mjs launchd > ~/Library/LaunchAgents/${LABEL}.plist
    launchctl load ~/Library/LaunchAgents/${LABEL}.plist
    launchctl list | grep watchfloor
-->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>

  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${escapeXml(wrapper)}</string>
  </array>

  <!-- The scheduler self-schedules its own ticks, so this is "keep the process
       alive", not "run me on a timer". KeepAlive restarts it after a crash, a
       failed migration, or a reboot. -->
  <key>KeepAlive</key>
  <true/>
  <key>RunAtLoad</key>
  <true/>

  <!-- launchd does NOT inherit a login shell's PATH. Without this, npm and node
       are simply not found and the agent fails in a way that looks like the app
       is broken. This is the most common launchd mistake there is. -->
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>${escapeXml(binDir)}:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>

  <key>WorkingDirectory</key>
  <string>${escapeXml(repoRoot)}</string>

  <key>StandardOutPath</key>
  <string>${escapeXml(join(logs, 'scheduler.log'))}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(join(logs, 'scheduler.error.log'))}</string>

  <!-- Don't hammer a broken deploy: 30s between restarts is enough to read a
       log and slow enough that a crash loop is visible rather than a spin. -->
  <key>ThrottleInterval</key>
  <integer>30</integer>

  <!-- Ingest is network I/O against other people's servers on a poll interval;
       it should never compete with whatever the operator is actually doing. -->
  <key>ProcessType</key>
  <string>Background</string>
  <key>Nice</key>
  <integer>5</integer>
</dict>
</plist>
`;
}

function systemd() {
  const logs = logDir();
  return `# Generated by scripts/generate-service.mjs on ${new Date().toISOString()}.
# Regenerate rather than editing: the paths below are this machine's.
#
#   node scripts/generate-service.mjs systemd > ~/.config/systemd/user/watchfloor.service
#   systemctl --user daemon-reload
#   systemctl --user enable --now watchfloor
#   journalctl --user -u watchfloor -f
#
# A USER unit, not a system one: everything runs as the owner, reads a .env in
# their home, and writes an Obsidian vault they own. A system unit would need
# all three to be root-readable, which is a downgrade for no benefit.
# Note "linger" is required for a user unit to run without an active login:
#   sudo loginctl enable-linger \$USER

[Unit]
Description=Watchfloor scheduler — polls sources, scores, and syncs the vault
Documentation=file://${join(repoRoot, 'README.md')}
After=network-online.target
Wants=network-online.target

[Service]
Type=exec
WorkingDirectory=${repoRoot}
ExecStart=/bin/sh ${wrapper}

# The wrapper runs the migration and then execs the scheduler, so systemd
# supervises node itself and SIGTERM reaches the scheduler's own handler, which
# closes the database cleanly.
Restart=always
RestartSec=30

# The scheduler is network I/O on a poll interval and must not compete with
# anything interactive.
Nice=5
IOSchedulingClass=idle

# journald already captures stdout/stderr; these are here only if the operator
# prefers files, matching the launchd agent's paths.
# StandardOutput=append:${join(logs, 'scheduler.log')}
# StandardError=append:${join(logs, 'scheduler.error.log')}

[Install]
WantedBy=default.target
`;
}

const kind = process.argv[2];
if (!existsSync(wrapper)) {
  console.error(`missing ${wrapper} — the supervisor config would point at nothing`);
  process.exit(1);
}
if (kind === 'launchd') {
  process.stdout.write(launchd());
} else if (kind === 'systemd') {
  process.stdout.write(systemd());
} else {
  console.error(
    'usage: node scripts/generate-service.mjs <launchd|systemd>\n' +
      '\n' +
      '  launchd  > ~/Library/LaunchAgents/io.dram51.watchfloor.scheduler.plist\n' +
      '  systemd  > ~/.config/systemd/user/watchfloor.service\n' +
      '\n' +
      'Both run scripts/scheduler-service.sh, which applies pending migrations\n' +
      'and then execs the scheduler. See that file for why those are one step.',
  );
  process.exit(1);
}
