import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { parse } from 'yaml';
import { z } from 'zod';
import type { LocationKind } from '../domain/location.ts';
// Generated by scripts/build-basemap.mjs from the SAME Natural Earth file the
// map renders, and committed. Imported rather than read from disk at runtime
// so the gazetteer has no file dependency a test or a packaged build could
// miss -- and so a country the choropleth can draw is always a country the
// matcher can attribute.
import countryData from './countries.json' with { type: 'json' };

/**
 * The gazetteer config: `config/locations.yaml` plus `config/jurisdictions.yaml`,
 * plus the optional, gitignored `config/locations.local.yaml` overlay.
 *
 * ## Why a location is a config row and never a geocoder call
 *
 * §7.2 is explicit: *"A curated, hand-maintained `locations` table -- do not
 * auto-geocode."* A geocoder answers "where is this string" with a plausible
 * coordinate for any string, including a wrong one, and the failure is silent:
 * a pin lands somewhere reasonable-looking and nothing reports that it is the
 * wrong fab. Every coordinate in this system therefore arrives through a
 * hand-written row carrying a citation (`source_url`) and a date
 * (`verified_at`), both mandatory, both surfaced in the UI.
 *
 * ## `precision` exists because a city centroid is a plausible wrong answer
 *
 * Not in the brief; added because the alternative is worse. Some facility
 * coordinates are known to the building, others only to the town. Rounding the
 * second kind to a site-precision pin would present a guess with the same
 * authority as a survey. `precision` makes the difference data, so the UI can
 * draw a point for `site` and an area for `city`/`region` rather than implying
 * an accuracy the row does not have.
 *
 * ## The rule that keeps this an infrastructure map rather than a news globe
 *
 * **An operator name alone never geolocates an item.** "NVIDIA announces Q3
 * results" is not news about Santa Clara, and a gazetteer that treats every
 * company mention as a location match produces exactly the company-mention map
 * §7.2 says not to build. Operator matching is only ever a *co-occurrence*
 * signal, and only alongside a place term -- see `src/locations/gazetteer.ts`,
 * which owns the matching and states the confidence tiers.
 */

export class LocationConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'LocationConfigError';
  }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** How accurately the stored coordinate locates the thing it names. */
export type LocationPrecision = 'site' | 'city' | 'region';

export interface LocationAlias {
  /** A spelling that attributes this location when it appears in item text. */
  term: string;
  /**
   * `exact` is case-sensitive; `loose` folds case. Same two modes and the same
   * meaning as `config/entities.yaml`'s aliases, deliberately -- one matching
   * vocabulary across both gazetteers is one thing to learn.
   */
  match: 'exact' | 'loose';
  /**
   * How strong a claim this spelling makes ON ITS OWN, declared by the person
   * who wrote the row rather than inferred by the matcher.
   *
   * "Veldhoven" is a near-certain reference to ASML's site; "Fab 18" is not,
   * because more than one company numbers a fab 18. Only the config author
   * knows which is which, so the number lives here. The matcher may LOWER it
   * (see gazetteer.ts) and never raises it.
   */
  confidence: number;
}

export interface LocationRule {
  locationId: string;
  name: string;
  kind: LocationKind;
  operator: string | null;
  /** ISO 3166-1 alpha-2, uppercase. Joins a location to its jurisdiction row. */
  country: string;
  lat: number;
  lon: number;
  precision: LocationPrecision;
  /**
   * The settlement or district this sits in, if the coordinate is a site.
   * Used for the operator+place co-occurrence tier: "Intel" plus "Chandler"
   * in one headline is a real location claim where "Intel" alone is not.
   */
  city: string | null;
  notes: string | null;
  sourceUrl: string;
  /** ISO date (YYYY-MM-DD). Surfaced in the UI so a stale pin is visibly stale. */
  verifiedAt: string;
  aliases: LocationAlias[];
  /**
   * Entity names from `config/entities.yaml` that refer to this site's
   * operator. This is the join that makes §7.2's *"click a ticker in the
   * market ribbon -> highlight that company's facilities"* possible, and the
   * relation the supply arcs are derived from.
   *
   * Validated against the entity ruleset by `assertEntityLinksResolve`, called
   * at boot where both configs are loaded. A dangling name here would be a
   * highlight that silently never fires -- this project's characteristic
   * defect, in miniature.
   */
  entities: string[];
}

/** Where a country sits in the export-control picture, from a US-rules perspective. */
export type ExportControlStatus =
  | 'unrestricted'
  | 'license_required'
  | 'restricted'
  | 'embargoed'
  | 'unknown';

/**
 * What a country contributes to the AI supply chain. Tags, not a hierarchy --
 * the Netherlands is `equipment` without `fab_capacity`, Taiwan is both.
 *
 * This is the field that makes the jurisdiction layer earn its place (§7.2):
 * a choropleth of control status alone re-states the news, whereas control
 * status crossed with what a country actually *makes* is the thing that is
 * hard to hold in your head from reading lanes.
 */
export type SupplyRole =
  | 'fab_capacity'
  | 'advanced_fab'
  | 'packaging'
  | 'equipment'
  | 'materials'
  | 'hyperscale_compute'
  | 'design';

export interface JurisdictionRule {
  /** ISO 3166-1 alpha-2, uppercase. */
  code: string;
  name: string;
  /** Spellings that attribute this country in item text, including demonyms. */
  aliases: LocationAlias[];
  exportControl: ExportControlStatus;
  roles: SupplyRole[];
  notes: string | null;
  sourceUrl: string;
  verifiedAt: string;
}

/**
 * Every country name in the vendored basemap, keyed by ISO alpha-2.
 *
 * Generated by `scripts/build-basemap.mjs` from the same Natural Earth file
 * the map draws, so a country the choropleth can render is always a country
 * the gazetteer can attribute -- one list, one build step, no drift.
 *
 * `config/jurisdictions.yaml` is the CURATED overlay on this: it adds
 * demonyms, tunes confidence, and carries the policy claims. A country with no
 * row there still matches by name and simply has no export-control colour --
 * which is the honest rendering of "nobody has checked this one."
 */
export type CountryNames = Readonly<Record<string, string>>;

const COUNTRY_NAMES: CountryNames = countryData.countries;

export interface GazetteerConfig {
  locations: LocationRule[];
  jurisdictions: JurisdictionRule[];
  countryNames: CountryNames;
  /**
   * §7.2: *"Never plot below the threshold."* One number, in config, applied
   * on the READ path as well as the write path -- a stored low-confidence
   * match is a fact we recorded, not a pin we drew.
   */
  minConfidence: number;
}

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

const LOCATION_KINDS = [
  'fab',
  'packaging',
  'datacenter',
  'colo',
  'cloud_region',
  'hq',
  'port',
] as const satisfies readonly LocationKind[];

const ID_RE = /^[a-z0-9][a-z0-9-]*$/;
const ISO_COUNTRY_RE = /^[A-Z]{2}$/;
const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

const DEFAULT_ALIAS_CONFIDENCE = 0.9;
const DEFAULT_MIN_CONFIDENCE = 0.6;

const trimmed = (label: string, max: number) =>
  z
    .string()
    .min(1, `${label} must not be empty`)
    .max(max, `${label} must be ${max} characters or fewer`)
    .refine((s) => s.trim() === s, `${label} must not have leading or trailing whitespace`);

const AliasSchema = z.union([
  trimmed('alias', 100).transform(
    (term): LocationAlias => ({ term, match: 'exact', confidence: DEFAULT_ALIAS_CONFIDENCE }),
  ),
  z
    .object({
      term: trimmed('alias term', 100),
      match: z.enum(['exact', 'loose']).default('exact'),
      confidence: z.number().gt(0).lte(1).default(DEFAULT_ALIAS_CONFIDENCE),
    })
    .transform(
      (a): LocationAlias => ({ term: a.term, match: a.match, confidence: a.confidence }),
    ),
]);

// A source_url must be http(s) and absolute. A citation that cannot be opened
// is not a citation, and this is the one field the whole "expect this file to
// be wrong and stale" contract rests on.
const SourceUrlSchema = z
  .string()
  .url('source_url must be an absolute URL')
  .refine(
    (u) => u.startsWith('http://') || u.startsWith('https://'),
    'source_url must be http or https',
  );

const VerifiedAtSchema = z
  .string()
  .regex(ISO_DATE_RE, 'verified_at must be an ISO date (YYYY-MM-DD)')
  .refine((d) => !Number.isNaN(Date.parse(`${d}T00:00:00Z`)), 'verified_at is not a real date');

const LocationSchema = z.object({
  // Not built from `trimmed()`: that helper ends in `.refine`, which returns a
  // ZodEffects with no `.regex` method. The regex already forbids whitespace.
  id: z
    .string()
    .max(80, 'id must be 80 characters or fewer')
    .regex(ID_RE, 'id must be lowercase letters, digits and hyphens, starting with a letter or digit'),
  name: trimmed('name', 120),
  kind: z.enum(LOCATION_KINDS),
  operator: trimmed('operator', 120).nullable().optional(),
  country: z.string().regex(ISO_COUNTRY_RE, 'country must be an uppercase ISO 3166-1 alpha-2 code'),
  // Bounds, not just "a number": a transposed lat/lon pair is the single most
  // common hand-entry error in geographic data, and a latitude of 120 is the
  // one shape of it a machine can catch.
  lat: z.number().gte(-90, 'lat must be between -90 and 90').lte(90, 'lat must be between -90 and 90'),
  lon: z
    .number()
    .gte(-180, 'lon must be between -180 and 180')
    .lte(180, 'lon must be between -180 and 180'),
  precision: z.enum(['site', 'city', 'region']),
  city: trimmed('city', 120).nullable().optional(),
  notes: trimmed('notes', 500).nullable().optional(),
  source_url: SourceUrlSchema,
  verified_at: VerifiedAtSchema,
  aliases: z.array(AliasSchema).default([]),
  entities: z.array(trimmed('entity', 100)).default([]),
});

const JurisdictionSchema = z.object({
  code: z.string().regex(ISO_COUNTRY_RE, 'code must be an uppercase ISO 3166-1 alpha-2 code'),
  name: trimmed('name', 120),
  aliases: z.array(AliasSchema).default([]),
  export_control: z.enum(['unrestricted', 'license_required', 'restricted', 'embargoed', 'unknown']),
  roles: z
    .array(
      z.enum([
        'fab_capacity',
        'advanced_fab',
        'packaging',
        'equipment',
        'materials',
        'hyperscale_compute',
        'design',
      ]),
    )
    .default([]),
  notes: trimmed('notes', 500).nullable().optional(),
  source_url: SourceUrlSchema,
  verified_at: VerifiedAtSchema,
});

const LocationsFileSchema = z.object({
  locations: z.array(LocationSchema),
});

const JurisdictionsFileSchema = z.object({
  min_confidence: z.number().gt(0).lte(1).default(DEFAULT_MIN_CONFIDENCE),
  countries: z.array(JurisdictionSchema),
});

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

function parseYaml(label: string, text: string): unknown {
  try {
    return parse(text);
  } catch (cause) {
    throw new LocationConfigError(`could not parse ${label}: ${(cause as Error).message}`);
  }
}

function fail(label: string, error: z.ZodError): never {
  const lines = error.issues.map((i) => `  ${i.path.join('.')}: ${i.message}`);
  throw new LocationConfigError(`invalid ${label}:\n${lines.join('\n')}`);
}

function toLocationRule(raw: z.infer<typeof LocationSchema>): LocationRule {
  return {
    locationId: raw.id,
    name: raw.name,
    kind: raw.kind,
    operator: raw.operator ?? null,
    country: raw.country,
    lat: raw.lat,
    lon: raw.lon,
    precision: raw.precision,
    city: raw.city ?? null,
    notes: raw.notes ?? null,
    sourceUrl: raw.source_url,
    verifiedAt: raw.verified_at,
    aliases: raw.aliases,
    entities: raw.entities,
  };
}

/**
 * Parse `config/locations.yaml` text. The overlay, if any, is merged by
 * `loadGazetteer` -- this function handles one document.
 */
export function loadLocations(yamlText: string, label = 'locations config'): LocationRule[] {
  const result = LocationsFileSchema.safeParse(parseYaml(label, yamlText));
  if (!result.success) fail(label, result.error);
  return result.data.locations.map(toLocationRule);
}

export function loadJurisdictions(
  yamlText: string,
  label = 'jurisdictions config',
): { minConfidence: number; jurisdictions: JurisdictionRule[] } {
  const result = JurisdictionsFileSchema.safeParse(parseYaml(label, yamlText));
  if (!result.success) fail(label, result.error);

  return {
    minConfidence: result.data.min_confidence,
    jurisdictions: result.data.countries.map((c) => ({
      code: c.code,
      name: c.name,
      aliases: c.aliases,
      exportControl: c.export_control,
      roles: c.roles,
      notes: c.notes ?? null,
      sourceUrl: c.source_url,
      verifiedAt: c.verified_at,
    })),
  };
}

// ---------------------------------------------------------------------------
// Cross-document validation
// ---------------------------------------------------------------------------

function assertConsistent(config: GazetteerConfig): void {
  const seenIds = new Set<string>();
  for (const loc of config.locations) {
    if (seenIds.has(loc.locationId)) {
      throw new LocationConfigError(
        `duplicate location id ${JSON.stringify(loc.locationId)}; the overlay REPLACES a base ` +
          `row with the same id, so two rows sharing an id inside ONE document is a mistake`,
      );
    }
    seenIds.add(loc.locationId);

    if (loc.precision === 'site' && loc.city === null) {
      // Not fatal in principle, but a site-precision row with no city cannot
      // participate in the operator+place matching tier, which is the tier
      // most facility mentions actually arrive through. Refusing it here is
      // cheaper than wondering later why a fab never matches anything.
      throw new LocationConfigError(
        `location ${JSON.stringify(loc.locationId)} has precision: site but no city; a site row ` +
          `needs a city to be reachable by operator+place matching`,
      );
    }
  }

  const countries = new Set(config.jurisdictions.map((j) => j.code));
  const seenCodes = new Set<string>();
  for (const j of config.jurisdictions) {
    if (seenCodes.has(j.code)) {
      throw new LocationConfigError(`duplicate jurisdiction code ${JSON.stringify(j.code)}`);
    }
    seenCodes.add(j.code);
  }

  for (const loc of config.locations) {
    if (!countries.has(loc.country)) {
      // The jurisdiction layer is a choropleth keyed on this code, and a pin
      // in a country with no jurisdiction row renders over a hole. Loud here,
      // invisible later.
      throw new LocationConfigError(
        `location ${JSON.stringify(loc.locationId)} is in country ${JSON.stringify(loc.country)}, ` +
          `which has no row in the jurisdictions config`,
      );
    }
  }

  // One alias spelling must not attribute two different locations: the matcher
  // would report both, and an item cannot be at two fabs because one word is
  // ambiguous. Same rule, same reasoning, as config/entities.yaml's alias
  // ownership check.
  const aliasOwner = new Map<string, string>();
  for (const loc of config.locations) {
    for (const alias of loc.aliases) {
      const key = alias.match === 'loose' ? alias.term.toLowerCase() : alias.term;
      const owner = aliasOwner.get(key);
      if (owner !== undefined && owner !== loc.locationId) {
        throw new LocationConfigError(
          `alias ${JSON.stringify(alias.term)} is claimed by both ${JSON.stringify(owner)} and ` +
            `${JSON.stringify(loc.locationId)}; one spelling cannot attribute two places`,
        );
      }
      aliasOwner.set(key, loc.locationId);
    }
  }
}

/**
 * Fail if a location's `entities` names something `config/entities.yaml` does
 * not define.
 *
 * Separate from `loadGazetteer` on purpose: the loader stays a pure function
 * of its own documents, and the cross-config check runs at boot where both are
 * in hand. Called by `src/bin/ingest.ts` and `src/bin/api.ts`.
 */
export function assertEntityLinksResolve(
  config: GazetteerConfig,
  knownEntityNames: ReadonlySet<string>,
): void {
  const dangling: string[] = [];
  for (const loc of config.locations) {
    for (const name of loc.entities) {
      if (!knownEntityNames.has(name)) dangling.push(`${loc.locationId} -> ${name}`);
    }
  }
  if (dangling.length > 0) {
    throw new LocationConfigError(
      `location entity links name entities that config/entities.yaml does not define:\n` +
        dangling.map((d) => `  ${d}`).join('\n') +
        `\nA dangling link is a facility highlight that silently never fires.`,
    );
  }
}

// ---------------------------------------------------------------------------
// Loading from disk
// ---------------------------------------------------------------------------

export interface GazetteerPaths {
  locations: string;
  jurisdictions: string;
  /**
   * The gitignored overlay. **Absent is normal** and never warned about --
   * see `config/locations.yaml`'s header for why the committed seed is
   * deliberately not the owner's holdings.
   */
  overlay?: string;
}

/**
 * Country names that are also ordinary English words, common given names, or
 * US place names, and therefore must NOT be matched from the generated list
 * alone.
 *
 * This is the same problem `config/entities.yaml` documents at length for
 * `Apache`, `Progress`, `Meta` and `SEC`, arriving from a different direction.
 * "Georgia" is a US state in most of this corpus; "Jordan" is usually a
 * person; "Turkey" is seasonal; "Chad" and "Mali" are names. A generated list
 * of 175 country names cannot know any of that.
 *
 * A name listed here scores below any usable threshold on its own. It becomes
 * matchable by writing an explicit row in `config/jurisdictions.yaml`, where a
 * human picks the spelling and states the confidence -- exactly how an
 * ambiguous entity alias is handled. The point is not that these countries are
 * unimportant; it is that attributing them needs a decision, not a default.
 */
const AMBIGUOUS_COUNTRY_NAMES = new Set([
  'Georgia',
  'Jordan',
  'Chad',
  'Niger',
  'Turkey',
  'Guinea',
  'Mali',
  'Oman',
  'Malta',
  'Grenada',
  'Dominica',
  'Palau',
  'Samoa',
  'Tonga',
  'Nauru',
  // Both of these name a country AND a region inside a larger one (South
  // Sudan, the two Congos), so a bare match attributes the wrong state often
  // enough to matter.
  'Congo',
  'Sudan',
]);

/**
 * Base confidence for a country name taken from the generated list with no
 * curated row behind it. Deliberately BELOW what a curated alias gets: an
 * unreviewed name is a weaker claim than one someone looked at.
 */
const GENERATED_COUNTRY_CONFIDENCE = 0.9;

/**
 * What an ambiguous name scores when nothing curated rescues it. Low enough to
 * sit under any sane `min_confidence`, so the match is STORED (it is evidence,
 * and the sweep records what it saw) and never PLOTTED.
 */
const AMBIGUOUS_COUNTRY_CONFIDENCE = 0.2;

/**
 * Merge the generated country list into the curated jurisdictions, producing
 * the rule set the gazetteer actually matches against.
 *
 * A curated row wins outright for its code: it already carries the alias list
 * its author chose, and silently appending the generated name to it would
 * reintroduce exactly the ambiguity the author was avoiding by omitting it.
 */
function withGeneratedCountries(
  curated: readonly JurisdictionRule[],
  countryNames: CountryNames,
): JurisdictionRule[] {
  const byCode = new Map(curated.map((j) => [j.code, j]));

  for (const [code, name] of Object.entries(countryNames)) {
    if (byCode.has(code)) continue;
    byCode.set(code, {
      code,
      name,
      aliases: [
        {
          term: name,
          // Loose: headline capitalisation of a country name is orthography,
          // not identity.
          match: 'loose',
          confidence: AMBIGUOUS_COUNTRY_NAMES.has(name)
            ? AMBIGUOUS_COUNTRY_CONFIDENCE
            : GENERATED_COUNTRY_CONFIDENCE,
        },
      ],
      // No policy claim, because nobody made one. `unknown` renders as "no
      // claim" rather than as a colour -- see config/jurisdictions.yaml's
      // header on why that is the correct value and not a gap to fill.
      exportControl: 'unknown',
      roles: [],
      notes: null,
      sourceUrl: 'https://www.naturalearthdata.com/about/terms-of-use/',
      // The basemap's own vintage, not a review date. Distinguishable from a
      // curated row at a glance, which is the point.
      verifiedAt: '2026-08-16',
    });
  }

  return [...byCode.values()].sort((a, b) => (a.code < b.code ? -1 : 1));
}

export function loadGazetteerFiles(paths: GazetteerPaths): GazetteerConfig {
  const base = loadLocations(readFileSync(paths.locations, 'utf8'), paths.locations);
  const { minConfidence, jurisdictions } = loadJurisdictions(
    readFileSync(paths.jurisdictions, 'utf8'),
    paths.jurisdictions,
  );

  let locations = base;
  if (paths.overlay !== undefined) {
    let overlayText: string | null = null;
    try {
      overlayText = readFileSync(paths.overlay, 'utf8');
    } catch (cause) {
      // ENOENT is the expected case, not an error. Anything else -- a
      // directory, a permissions failure -- is a real problem and must not be
      // swallowed into "no overlay configured".
      if ((cause as NodeJS.ErrnoException).code !== 'ENOENT') throw cause;
    }
    if (overlayText !== null) {
      const overlay = loadLocations(overlayText, paths.overlay);
      const byId = new Map(base.map((l) => [l.locationId, l]));
      for (const row of overlay) byId.set(row.locationId, row);
      locations = [...byId.values()];
    }
  }

  const config: GazetteerConfig = {
    locations,
    jurisdictions: withGeneratedCountries(jurisdictions, COUNTRY_NAMES),
    countryNames: COUNTRY_NAMES,
    minConfidence,
  };
  assertConsistent(config);
  return config;
}

// ---------------------------------------------------------------------------
// gazetteerVersion
// ---------------------------------------------------------------------------

/**
 * A content digest of everything that can change what the gazetteer extracts.
 *
 * Identical mechanism and identical reasoning to `rulesetVersion` in
 * `src/entities/rules.ts`: without it, adding a location to config would only
 * ever affect items ingested afterwards, and the 16,570 items already stored
 * would keep whatever the gazetteer said the day they arrived. Editing config
 * changes this digest, which empties the sweep's "already done" set, which
 * re-opens the whole corpus over the next few polls.
 *
 * Derived, never hand-maintained -- a version someone must remember to bump is
 * a version that is eventually wrong while looking right.
 *
 * Order-insensitive, so reordering config for readability costs nothing.
 * `minConfidence` IS included: lowering it changes which matches are stored.
 * Presentation-only fields (`notes`, `sourceUrl`, `verifiedAt`, `precision`)
 * are deliberately EXCLUDED -- correcting a citation or re-verifying a pin
 * must not trigger a 16,570-item re-extraction that cannot produce a different
 * answer.
 */
export function gazetteerVersion(config: GazetteerConfig): string {
  const alias = (a: LocationAlias) => [a.term, a.match, a.confidence] as const;
  const byTerm = (x: readonly [string, ...unknown[]], y: readonly [string, ...unknown[]]) =>
    x[0] < y[0] ? -1 : x[0] > y[0] ? 1 : 0;

  const canonical = {
    minConfidence: config.minConfidence,
    locations: [...config.locations]
      .map((l) => ({
        id: l.locationId,
        kind: l.kind,
        operator: l.operator,
        country: l.country,
        city: l.city,
        lat: l.lat,
        lon: l.lon,
        name: l.name,
        entities: [...l.entities].sort(),
        aliases: l.aliases.map(alias).sort(byTerm),
      }))
      .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0)),
    jurisdictions: [...config.jurisdictions]
      .map((j) => ({
        code: j.code,
        name: j.name,
        aliases: j.aliases.map(alias).sort(byTerm),
      }))
      .sort((a, b) => (a.code < b.code ? -1 : a.code > b.code ? 1 : 0)),
  };

  return createHash('sha256').update(JSON.stringify(canonical), 'utf8').digest('hex').slice(0, 16);
}
